import { readFile, writeFile, mkdtemp, mkdir, readdir, rm, rename, stat } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const project = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'));
const output = join(root, 'theme-api');
const staging = await mkdtemp(join(root, '.gloria-api-build-'));
const assets = join(staging, 'dist/assets');
const serviceName = 'v3-services-BR8Lph9F.js';

function replaceOnce(source, before, after) {
  if (source.split(before).length !== 2) throw new Error(`Expected one match: ${before.slice(0, 100)}`);
  return source.replace(before, () => after);
}

try {
  // Always start from the supplied archive; repeated builds never patch a patched bundle.
  execFileSync('python3', ['-c', `
import pathlib, sys, tarfile
with tarfile.open(sys.argv[1], 'r:gz') as archive:
    for member in archive.getmembers():
        assert not member.name.startswith('/') and '..' not in pathlib.Path(member.name).parts
        assert member.isfile() or member.isdir()
    archive.extractall(sys.argv[2], filter='data')
`, join(root, 'upstream/theme.tar.gz'), staging]);

  const original = await import(pathToFileURL(join(assets, serviceName)));
  const packedConfig = JSON.parse(await readFile(join(staging, 'dist/theme-config.json'), 'utf8'));
  const checked = original.v(packedConfig);
  if (Object.keys(checked.errors).length) throw new Error('The original package contains invalid configuration.');
  const manifest = JSON.parse(await readFile(join(staging, 'theme.json'), 'utf8'));
  manifest.version = project.version;
  manifest.url = project.repository?.url ?? '';
  manifest.config = [];
  const jsonKeys = [];
  const uiOrder = [];
  for (const group of original.t) {
    manifest.config.push({ type: 'title', label: group.name });
    uiOrder.push({ type: 'title', name: group.name });
    for (const field of group.fields) {
      if (field.disabled) {
        uiOrder.push(field);
        continue;
      }
      uiOrder.push(field.key);
      const next = {
        key: field.key,
        type: ({ switch: 'boolean', richtext: 'text' })[field.type] ?? field.type,
        label: field.name,
        default: checked.config[field.key],
        help: field.help,
      };
      if (field.options) next.options = field.options.map((value) => ({ value, label: value }));
      if (field.min !== undefined) next.min = field.min;
      if (field.max !== undefined) next.max = field.max;
      if (field.json) jsonKeys.push(field.key);
      manifest.config.push(next);
    }
  }
  await writeFile(join(staging, 'theme.json'), JSON.stringify(manifest, null, 2) + '\n');
  await writeFile(join(staging, 'dist/theme-config.json'), JSON.stringify(checked.config, null, 2) + '\n');
  // Generate the browser schema from the same declarations the hub panel reads.
  await writeFile(join(assets, 'theme-config-schema.js'), `// Generated by scripts/build-theme.mjs from theme.json.\nexport const themeShort = ${JSON.stringify(manifest.short)};\nexport const configFields = ${JSON.stringify(manifest.config)};\nexport const jsonKeys = ${JSON.stringify(jsonKeys)};\nconst uiOrder = ${JSON.stringify(uiOrder)};\nconst byKey = new Map(configFields.filter(f => f.key).map(f => [f.key, f]));\nexport const themeSettingsSchema = uiOrder.map(entry => {\n  if (typeof entry !== 'string') return entry;\n  const field = byKey.get(entry);\n  return { ...field, name: field.label, type: ({boolean:'switch',text:'richtext'})[field.type] ?? field.type, options: field.options?.map(option => option.value), json: jsonKeys.includes(field.key) };\n});\n`);
  await writeFile(join(assets, 'theme-config-api.js'), await readFile(join(root, 'src/theme-config-api.js')));
  await writeFile(join(assets, 'theme-persistence.service-CzeQdFWu.js'), await readFile(join(root, 'src/theme-persistence.service.js')));

  let service = await readFile(join(assets, serviceName), 'utf8');
  const schemaStart = service.indexOf('Dr=JSON.parse(');
  const schemaEnd = service.indexOf(',sn=256*1024', schemaStart);
  if (schemaStart < 0 || schemaEnd < 0) throw new Error('Original settings schema not found.');
  service = service.slice(0, schemaStart) + 'Dr=themeSettingsSchema' + service.slice(schemaEnd);
  const uploadStart = service.indexOf('async function Ls(');
  const uploadEnd = service.indexOf('async function Bt(', uploadStart);
  if (uploadStart < 0 || uploadEnd < 0) throw new Error('Original upload service not found.');
  service = service.slice(0, uploadStart) + service.slice(uploadEnd);
  service = replaceOnce(service, 'Ls as a3,', '');
  const loadStart = service.indexOf('function cn()');
  const loadEnd = service.indexOf('class Ir', loadStart);
  if (loadStart < 0 || loadEnd < 0) throw new Error('Original config loader not found.');
  service = service.slice(0, loadStart) + 'function cn(options){return loadThemeConfig(options)}' + service.slice(loadEnd);
  service = replaceOnce(service, 'async function g(){const c=await cn();', 'async function g(){const c=await cn({strict:true});');
  service = 'import {themeSettingsSchema} from "./theme-config-schema.js";\nimport {loadThemeConfig} from "./theme-config-api.js";\n' + service;
  await writeFile(join(assets, serviceName), service);

  const dialogPath = join(assets, 'ThemeSettingsDialog-mrIsewmu.js');
  let dialog = await readFile(dialogPath, 'utf8');
  dialog = replaceOnce(dialog, '__vite__mapDeps([0,1,2,3,4])', '__vite__mapDeps([0,1,2,3])');
  dialog = replaceOnce(dialog, '正在保存到服务器，请保持页面打开。', '正在保存主题设置。');
  dialog = replaceOnce(dialog, '下载已配置主题包', '下载主题与配置备份');
  dialog = replaceOnce(dialog, '已下载 theme.tar.gz 配置备份；服务器配置未改变。', '已下载主题与配置备份；恢复设置时请导入包内的 dist/theme-config.json 并保存。');
  await writeFile(dialogPath, dialog);

  // Rename the complete JS dependency graph so browsers cannot reuse pre-migration chunks.
  const jsFiles = (await readdir(assets)).filter((name) => name.endsWith('.js')).sort();
  const contents = new Map(await Promise.all(jsFiles.map(async (name) => [name, await readFile(join(assets, name), 'utf8')])));
  const revision = createHash('sha256').update([...contents.values()].join('\n')).digest('hex').slice(0, 10);
  const renames = new Map(jsFiles.map((name) => [name, name.slice(0, -3) + `-api-${revision}.js`]));
  function updateReferences(text) {
    for (const [before, after] of renames) text = text.replaceAll(before, after);
    return text;
  }
  for (const [name, content] of contents) {
    await writeFile(join(assets, renames.get(name)), updateReferences(content));
    await rm(join(assets, name));
  }
  const index = join(staging, 'dist/index.html');
  await writeFile(index, updateReferences(await readFile(index, 'utf8')));

  const packagePath = join(staging, 'dist/theme-package.json');
  const packageInfo = JSON.parse(await readFile(packagePath, 'utf8'));
  packageInfo.manifest = manifest;
  packageInfo.files = [];
  async function collect(dir, prefix = '') {
    for (const entry of (await readdir(dir, { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name))) {
      const name = prefix + entry.name;
      if (entry.isDirectory()) await collect(join(dir, entry.name), name + '/');
      else if (!['theme-package.json', 'theme-config.json'].includes(name)) {
        const data = await readFile(join(dir, entry.name));
        if (data.length > 8 * 1024 * 1024) throw new Error(`File exceeds hub limit: ${name}`);
        packageInfo.files.push({ name, bytes: data.length, sha256: createHash('sha256').update(data).digest('hex') });
      }
    }
  }
  await collect(join(staging, 'dist'));
  await writeFile(packagePath, JSON.stringify(packageInfo) + '\n');
  await mkdir(output, { recursive: true });
  await rm(output, { recursive: true });
  await rename(staging, output);
  const archive = join(root, 'theme-api.tar.gz');
  execFileSync('tar', ['--sort=name', '--mtime=@0', '--owner=0', '--group=0', '--numeric-owner', '-czf', archive, '-C', output, 'theme.json', 'LICENSE', 'preview.png', 'dist']);
  if ((await stat(archive)).size > 32 * 1024 * 1024) throw new Error('Archive exceeds hub limit.');
  const checksum = createHash('sha256').update(await readFile(archive)).digest('hex');
  await writeFile(archive + '.sha256', `${checksum}  theme-api.tar.gz\n`);
  console.log(`Built ${archive}: ${manifest.config.filter(f => f.key).length} settings, revision ${revision}`);
} finally {
  await rm(staging, { recursive: true, force: true });
}
